server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/cloud?useSSL=false
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8
    username: root
    password: 1106135
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: userserver  # user的服务名称
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848  # nacos服务地址
#      discovery:
#        cluster-name: HZ  # 集群名称，这里HZ代指杭州集群

#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: com.shubao.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.shubao: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS