server:
  port: 8080
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/cloud?useSSL=false
    url: jdbc:mysql://localhost:3306/cloud?characterEncoding=utf8
    username: root
    password: 1106135
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: orderserver  # order的服务名称
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848  # nacos服务地址
#      discovery:
#        cluster-name: HZ  # 集群名称
#        # 不同的namespace访问会报错：  java.lang.IllegalStateException: No instances available for userserver
#        # namespace: 05803a2c-1dcf-49cb-bfdb-26920069534b  # 命名空间，填ID
#        ephemeral: false  # 是否是临时实例

#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: com.shubao.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.shubao: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

# 负载均衡策略配置：局部配置，orderserver只针对某个服务而言
userserver:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 负载均衡规则
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true  # 开启饥饿加载
    clients: userserver  # 指定饥饿加载的服务名称

# feign日志配置：通过配置文件的方式
feign:
#  client:
#    config:
#      default:
#        logger-level: FULL
  httpclient:
    enabled: true  # 开启HttpCLient
    max-connections: 200  # 最大连接数
    max-connections-per-route: 50  # 单个路径的最大连接数

