server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
#      server-addr: 127.0.0.1:8848  # nacos地址
      server-addr: 127.0.0.1:80  # nacos地址  这里走nacos集群，使用Nginx做负载均衡，与orderserver、userserver一样
    gateway:
      routes:
        - id: user-server  # 路由标志，自定义，必须唯一
          #uri: http:127.0.0.1:8081  # 路由的目标地址，http表示固定地址，不推荐
          uri: lb://userserver  # 路由的目标地址，lb:load balance 负载均衡
          predicates:  # 路由断言，判断请求是否符合规则
            - Path=/user/**  # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: order-server
          uri: lb://orderserver
          predicates:
            - Path=/order/**
            - After=2023-06-29T12:41:42.438236444+08:00[Asia/Shanghai]

