server:
  port: 10086  # 服务端口
spring:
  application:
    name: eurekaserver  # eureka的服务名称
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
    # https://www.cnblogs.com/archimedes-euler/p/9975563.html
    # Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，出现冲突，所以我们需要禁用它自己的客户端注册行为。
    # 参考：https://blog.csdn.net/feixiangzaitianye/article/details/97631144
    register-with-eureka: true  # 是否向eureka注册自身服务
    fetch-registry: false  # 是否检索服务
